### ISSUE TITLE
`asdf install dart latest` no longer downloads the latest version of Dart

### ISSUE THREAD

**Issue by SuperSonicHub1** [PatOConnor43/asdf-dart#11]
The current latest version of Dart is 2.10.4, but `asdf latest dart` returns `2.9.3`. Looking at the URL you use to get available versions, it quickly becomes obvious why your method has stopped working:
```json
...
"channels/stable/release/2.9.1/",
"channels/stable/release/2.9.2/",
"channels/stable/release/2.9.3/",
"channels/stable/release/29803/",
"channels/stable/release/30036/",
"channels/stable/release/30107/",
...
```
Luckily `asdf install dart 2.10.4` still works just fine.

**Comment by PatOConnor43** [comment]
I didn't realize asdf even supported "latest" as a version but it looks like they added support for that. However, latest probably isn't what you want either since right now "latest" would actually point to `2.12.0-133.2.beta`. I'll work on fixing this because you're right. `asdf latest dart` does return `2.9.3` but I also don't think you want to use "latest".

**Comment by PatOConnor43** [comment]
@SuperSonicHub1 I just merged something that I think should fix the issue and also added the ability to ignore the dev and beta channels. Check the README if you're interested and please make another issue if something comes up. Thanks.

**Comment by SuperSonicHub1** [comment]
Whoa, dude! Didn't think you'd fix this so quickly! Glad I created an issue.

**Comment by PatOConnor43** [comment]
No problem. Thanks for the report. :+1:
